// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20200418191953_up = [
  InsertTable('ServiceRequest'),
  InsertTable('Customer'),
  InsertTable('ServiceRequestText'),
  InsertTable('Address'),
  InsertTable('ServiceRequestItem'),
  InsertTable('Employee'),
  InsertColumn('object_id', Column.varchar, onTable: 'ServiceRequest', unique: true),
  InsertColumn('service_request_i_d', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('subject', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('in_warranty', Column.boolean, onTable: 'ServiceRequest'),
  InsertColumn('product_id', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('technician_id', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('customer_id', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('serial_number', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('planned_start_date', Column.datetime, onTable: 'ServiceRequest'),
  InsertColumn('planned_end_date', Column.datetime, onTable: 'ServiceRequest'),
  InsertColumn('actual_visit_start_date', Column.datetime, onTable: 'ServiceRequest'),
  InsertColumn('actual_visit_end_date', Column.datetime, onTable: 'ServiceRequest'),
  InsertColumn('payment_amount', Column.Double, onTable: 'ServiceRequest'),
  InsertColumn('payment_i_d', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('payment_status', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('payment_method', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('planned_amount', Column.Double, onTable: 'ServiceRequest'),
  InsertColumn('actual_amount', Column.Double, onTable: 'ServiceRequest'),
  InsertColumn('max_amount', Column.Double, onTable: 'ServiceRequest'),
  InsertColumn('fault_code_key', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('component_code', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('defect_code', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('fault_reported', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('error_code', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('action_taken', Column.varchar, onTable: 'ServiceRequest'),
  InsertColumn('object_id', Column.varchar, onTable: 'Customer'),
  InsertColumn('customer_id', Column.varchar, onTable: 'Customer'),
  InsertColumn('first_name', Column.varchar, onTable: 'Customer'),
  InsertColumn('last_name', Column.varchar, onTable: 'Customer'),
  InsertColumn('country', Column.varchar, onTable: 'Customer'),
  InsertColumn('city', Column.varchar, onTable: 'Customer'),
  InsertColumn('mobile_number', Column.varchar, onTable: 'Customer'),
  InsertColumn('street', Column.varchar, onTable: 'Customer'),
  InsertColumn('email', Column.varchar, onTable: 'Customer'),
  InsertColumn('language', Column.varchar, onTable: 'Customer'),
  InsertColumn('object_id', Column.varchar, onTable: 'ServiceRequestText'),
  InsertColumn('parent_object_id', Column.varchar, onTable: 'ServiceRequestText'),
  InsertColumn('text', Column.varchar, onTable: 'ServiceRequestText'),
  InsertColumn('type_code', Column.varchar, onTable: 'ServiceRequestText'),
  InsertColumn('service_request_id', Column.varchar, onTable: 'ServiceRequestText'),
  InsertColumn('parent_object_id', Column.varchar, onTable: 'Address'),
  InsertColumn('city', Column.varchar, onTable: 'Address'),
  InsertColumn('street', Column.varchar, onTable: 'Address'),
  InsertColumn('email', Column.varchar, onTable: 'Address'),
  InsertColumn('country', Column.varchar, onTable: 'Address'),
  InsertColumn('country_text', Column.varchar, onTable: 'Address'),
  InsertColumn('phone', Column.varchar, onTable: 'Address'),
  InsertColumn('mobile', Column.varchar, onTable: 'Address'),
  InsertColumn('item_id', Column.varchar, onTable: 'ServiceRequestItem'),
  InsertColumn('object_id', Column.varchar, onTable: 'ServiceRequestItem'),
  InsertColumn('parent_id', Column.varchar, onTable: 'ServiceRequestItem'),
  InsertColumn('planned_quantity', Column.Double, onTable: 'ServiceRequestItem'),
  InsertColumn('actual_quantity', Column.Double, onTable: 'ServiceRequestItem'),
  InsertColumn('technician_id', Column.varchar, onTable: 'ServiceRequestItem'),
  InsertColumn('part_id', Column.varchar, onTable: 'ServiceRequestItem'),
  InsertColumn('part_description', Column.varchar, onTable: 'ServiceRequestItem'),
  InsertColumn('processing_type_code', Column.varchar, onTable: 'ServiceRequestItem'),
  InsertColumn('coverage_code', Column.varchar, onTable: 'ServiceRequestItem'),
  InsertColumn('object_id', Column.varchar, onTable: 'Employee'),
  InsertColumn('employee_id', Column.varchar, onTable: 'Employee'),
  InsertColumn('first_name', Column.varchar, onTable: 'Employee'),
  InsertColumn('last_name', Column.varchar, onTable: 'Employee'),
  InsertColumn('country', Column.varchar, onTable: 'Employee'),
  InsertColumn('city', Column.varchar, onTable: 'Employee'),
  InsertColumn('mobile_number', Column.varchar, onTable: 'Employee'),
  InsertColumn('street', Column.varchar, onTable: 'Employee'),
  InsertColumn('email', Column.varchar, onTable: 'Employee'),
  InsertColumn('language', Column.varchar, onTable: 'Employee')
];

const List<MigrationCommand> _migration_20200418191953_down = [
  DropTable('ServiceRequest'),
  DropTable('Customer'),
  DropTable('ServiceRequestText'),
  DropTable('Address'),
  DropTable('ServiceRequestItem'),
  DropTable('Employee'),
  DropColumn('object_id', onTable: 'ServiceRequest'),
  DropColumn('service_request_i_d', onTable: 'ServiceRequest'),
  DropColumn('subject', onTable: 'ServiceRequest'),
  DropColumn('in_warranty', onTable: 'ServiceRequest'),
  DropColumn('product_id', onTable: 'ServiceRequest'),
  DropColumn('technician_id', onTable: 'ServiceRequest'),
  DropColumn('customer_id', onTable: 'ServiceRequest'),
  DropColumn('serial_number', onTable: 'ServiceRequest'),
  DropColumn('planned_start_date', onTable: 'ServiceRequest'),
  DropColumn('planned_end_date', onTable: 'ServiceRequest'),
  DropColumn('actual_visit_start_date', onTable: 'ServiceRequest'),
  DropColumn('actual_visit_end_date', onTable: 'ServiceRequest'),
  DropColumn('payment_amount', onTable: 'ServiceRequest'),
  DropColumn('payment_i_d', onTable: 'ServiceRequest'),
  DropColumn('payment_status', onTable: 'ServiceRequest'),
  DropColumn('payment_method', onTable: 'ServiceRequest'),
  DropColumn('planned_amount', onTable: 'ServiceRequest'),
  DropColumn('actual_amount', onTable: 'ServiceRequest'),
  DropColumn('max_amount', onTable: 'ServiceRequest'),
  DropColumn('fault_code_key', onTable: 'ServiceRequest'),
  DropColumn('component_code', onTable: 'ServiceRequest'),
  DropColumn('defect_code', onTable: 'ServiceRequest'),
  DropColumn('fault_reported', onTable: 'ServiceRequest'),
  DropColumn('error_code', onTable: 'ServiceRequest'),
  DropColumn('action_taken', onTable: 'ServiceRequest'),
  DropColumn('object_id', onTable: 'Customer'),
  DropColumn('customer_id', onTable: 'Customer'),
  DropColumn('first_name', onTable: 'Customer'),
  DropColumn('last_name', onTable: 'Customer'),
  DropColumn('country', onTable: 'Customer'),
  DropColumn('city', onTable: 'Customer'),
  DropColumn('mobile_number', onTable: 'Customer'),
  DropColumn('street', onTable: 'Customer'),
  DropColumn('email', onTable: 'Customer'),
  DropColumn('language', onTable: 'Customer'),
  DropColumn('object_id', onTable: 'ServiceRequestText'),
  DropColumn('parent_object_id', onTable: 'ServiceRequestText'),
  DropColumn('text', onTable: 'ServiceRequestText'),
  DropColumn('type_code', onTable: 'ServiceRequestText'),
  DropColumn('service_request_id', onTable: 'ServiceRequestText'),
  DropColumn('parent_object_id', onTable: 'Address'),
  DropColumn('city', onTable: 'Address'),
  DropColumn('street', onTable: 'Address'),
  DropColumn('email', onTable: 'Address'),
  DropColumn('country', onTable: 'Address'),
  DropColumn('country_text', onTable: 'Address'),
  DropColumn('phone', onTable: 'Address'),
  DropColumn('mobile', onTable: 'Address'),
  DropColumn('item_id', onTable: 'ServiceRequestItem'),
  DropColumn('object_id', onTable: 'ServiceRequestItem'),
  DropColumn('parent_id', onTable: 'ServiceRequestItem'),
  DropColumn('planned_quantity', onTable: 'ServiceRequestItem'),
  DropColumn('actual_quantity', onTable: 'ServiceRequestItem'),
  DropColumn('technician_id', onTable: 'ServiceRequestItem'),
  DropColumn('part_id', onTable: 'ServiceRequestItem'),
  DropColumn('part_description', onTable: 'ServiceRequestItem'),
  DropColumn('processing_type_code', onTable: 'ServiceRequestItem'),
  DropColumn('coverage_code', onTable: 'ServiceRequestItem'),
  DropColumn('object_id', onTable: 'Employee'),
  DropColumn('employee_id', onTable: 'Employee'),
  DropColumn('first_name', onTable: 'Employee'),
  DropColumn('last_name', onTable: 'Employee'),
  DropColumn('country', onTable: 'Employee'),
  DropColumn('city', onTable: 'Employee'),
  DropColumn('mobile_number', onTable: 'Employee'),
  DropColumn('street', onTable: 'Employee'),
  DropColumn('email', onTable: 'Employee'),
  DropColumn('language', onTable: 'Employee')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20200418191953',
  up: _migration_20200418191953_up,
  down: _migration_20200418191953_down,
)
class Migration20200418191953 extends Migration {
  const Migration20200418191953()
    : super(
        version: 20200418191953,
        up: _migration_20200418191953_up,
        down: _migration_20200418191953_down,
      );
}
